# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mahya/Desktop/ECE0302/Projects/P2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mahya/Desktop/ECE0302/Projects/P2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahya/Desktop/ECE0302/Projects/P2/CMakeFiles /home/mahya/Desktop/ECE0302/Projects/P2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahya/Desktop/ECE0302/Projects/P2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named submission

# Build rule for target.
submission: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 submission
.PHONY : submission

# fast build rule for target.
submission/fast:
	$(MAKE) -f CMakeFiles/submission.dir/build.make CMakeFiles/submission.dir/build
.PHONY : submission/fast

#=============================================================================
# Target rules for targets named FindPalindrome-main

# Build rule for target.
FindPalindrome-main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FindPalindrome-main
.PHONY : FindPalindrome-main

# fast build rule for target.
FindPalindrome-main/fast:
	$(MAKE) -f CMakeFiles/FindPalindrome-main.dir/build.make CMakeFiles/FindPalindrome-main.dir/build
.PHONY : FindPalindrome-main/fast

#=============================================================================
# Target rules for targets named FindPalindrome-tests

# Build rule for target.
FindPalindrome-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FindPalindrome-tests
.PHONY : FindPalindrome-tests

# fast build rule for target.
FindPalindrome-tests/fast:
	$(MAKE) -f CMakeFiles/FindPalindrome-tests.dir/build.make CMakeFiles/FindPalindrome-tests.dir/build
.PHONY : FindPalindrome-tests/fast

FindPalindrome.o: FindPalindrome.cpp.o

.PHONY : FindPalindrome.o

# target to build an object file
FindPalindrome.cpp.o:
	$(MAKE) -f CMakeFiles/FindPalindrome-main.dir/build.make CMakeFiles/FindPalindrome-main.dir/FindPalindrome.cpp.o
	$(MAKE) -f CMakeFiles/FindPalindrome-tests.dir/build.make CMakeFiles/FindPalindrome-tests.dir/FindPalindrome.cpp.o
.PHONY : FindPalindrome.cpp.o

FindPalindrome.i: FindPalindrome.cpp.i

.PHONY : FindPalindrome.i

# target to preprocess a source file
FindPalindrome.cpp.i:
	$(MAKE) -f CMakeFiles/FindPalindrome-main.dir/build.make CMakeFiles/FindPalindrome-main.dir/FindPalindrome.cpp.i
	$(MAKE) -f CMakeFiles/FindPalindrome-tests.dir/build.make CMakeFiles/FindPalindrome-tests.dir/FindPalindrome.cpp.i
.PHONY : FindPalindrome.cpp.i

FindPalindrome.s: FindPalindrome.cpp.s

.PHONY : FindPalindrome.s

# target to generate assembly for a file
FindPalindrome.cpp.s:
	$(MAKE) -f CMakeFiles/FindPalindrome-main.dir/build.make CMakeFiles/FindPalindrome-main.dir/FindPalindrome.cpp.s
	$(MAKE) -f CMakeFiles/FindPalindrome-tests.dir/build.make CMakeFiles/FindPalindrome-tests.dir/FindPalindrome.cpp.s
.PHONY : FindPalindrome.cpp.s

FindPalindrome_main.o: FindPalindrome_main.cpp.o

.PHONY : FindPalindrome_main.o

# target to build an object file
FindPalindrome_main.cpp.o:
	$(MAKE) -f CMakeFiles/FindPalindrome-main.dir/build.make CMakeFiles/FindPalindrome-main.dir/FindPalindrome_main.cpp.o
.PHONY : FindPalindrome_main.cpp.o

FindPalindrome_main.i: FindPalindrome_main.cpp.i

.PHONY : FindPalindrome_main.i

# target to preprocess a source file
FindPalindrome_main.cpp.i:
	$(MAKE) -f CMakeFiles/FindPalindrome-main.dir/build.make CMakeFiles/FindPalindrome-main.dir/FindPalindrome_main.cpp.i
.PHONY : FindPalindrome_main.cpp.i

FindPalindrome_main.s: FindPalindrome_main.cpp.s

.PHONY : FindPalindrome_main.s

# target to generate assembly for a file
FindPalindrome_main.cpp.s:
	$(MAKE) -f CMakeFiles/FindPalindrome-main.dir/build.make CMakeFiles/FindPalindrome-main.dir/FindPalindrome_main.cpp.s
.PHONY : FindPalindrome_main.cpp.s

FindPalindrome_test.o: FindPalindrome_test.cpp.o

.PHONY : FindPalindrome_test.o

# target to build an object file
FindPalindrome_test.cpp.o:
	$(MAKE) -f CMakeFiles/FindPalindrome-tests.dir/build.make CMakeFiles/FindPalindrome-tests.dir/FindPalindrome_test.cpp.o
.PHONY : FindPalindrome_test.cpp.o

FindPalindrome_test.i: FindPalindrome_test.cpp.i

.PHONY : FindPalindrome_test.i

# target to preprocess a source file
FindPalindrome_test.cpp.i:
	$(MAKE) -f CMakeFiles/FindPalindrome-tests.dir/build.make CMakeFiles/FindPalindrome-tests.dir/FindPalindrome_test.cpp.i
.PHONY : FindPalindrome_test.cpp.i

FindPalindrome_test.s: FindPalindrome_test.cpp.s

.PHONY : FindPalindrome_test.s

# target to generate assembly for a file
FindPalindrome_test.cpp.s:
	$(MAKE) -f CMakeFiles/FindPalindrome-tests.dir/build.make CMakeFiles/FindPalindrome-tests.dir/FindPalindrome_test.cpp.s
.PHONY : FindPalindrome_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... submission"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... FindPalindrome-main"
	@echo "... FindPalindrome-tests"
	@echo "... FindPalindrome.o"
	@echo "... FindPalindrome.i"
	@echo "... FindPalindrome.s"
	@echo "... FindPalindrome_main.o"
	@echo "... FindPalindrome_main.i"
	@echo "... FindPalindrome_main.s"
	@echo "... FindPalindrome_test.o"
	@echo "... FindPalindrome_test.i"
	@echo "... FindPalindrome_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

